### ISSUE TITLE
Add file format metadata

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#1]
File-format analysis tools for archivists > https://lwn.net/Articles/688396/

**Comment by 7048730** [comment]
Which element should carry that information?

```.R``` files would be [```text/plain```](http://www.digipres.org/formats/mime-types/#text/plain)
```.Rmd``` files would be [```text/markdown```](http://www.digipres.org/formats/mime-types/#text/markdown)

Ofc we might also encounter a lot of different mime types in the data, such as ```image/tiff```

**Comment by 7048730** [comment]
included with 3c3a8e312223cd754928d5f503f0312e43bb109f
