### ISSUE TITLE
Extract temporal information

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#11]
To support searching using "time"-aspects of ERC, we need to extract this information.

_What is the desired information?_

- a "temporal bounding box"
- a single time instant at a specific level (e.g. "year")

**Sources for information:**

- [x] file dates
- [x] data fields (rdata file, netcdf or tabular data with timestamps)
- [x] document headers (RMarkdown?)

**Comment by 7048730** [comment]
```(json)
{
"temporal": {
 "begin": "$isotimestamp",
 "end": "$isotimestamp"
 }
}
```
