### ISSUE TITLE
Don't use primitives in arrays

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-meta#13]
AngularJS has problems binding to primitives. Therefore `arrays containing strings` should be changed to `arrays containing objects` to work properly on client side. I suggest following schema: 
```
"key": [{"name": String}, {"name": String}]
```
Here an example for the `keywords`-attribute:

```json
"keywords": [{"name": "reproducible"}, {"name": "research"}]
```

**Comment by 7048730** [comment]
well, I can't ask you to abandon angular but this is really bad for a JS dialect that cannot cope with js-objects haha

I will change it for your convenience...

**Comment by jansule** [comment]
In which way are you going to implement it? In [this issue](https://github.com/o2r-project/o2r-platform/issues/34) you stated a different opinion.

**Comment by 7048730** [comment]
We discussed this yesterday and go for simple arrays `["item", "item", ...]` and empty arrays `[]` in case nothing is found respectively..
