### ISSUE TITLE
Author as object

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-meta#14]
The actual version of the meta extraction creates author metadata like this:
```json
"o2r":{
            "orcid": "0000-0002-5728-0264",
            "author": "Ted Tester"
         }
```

Instead, it would make more sense to create an `author object` with its properties inside an `array`. Just like you specify on your documentation. Otherwise it won't be possible to have multiple authors.

Here an example:
```json
"o2r":{
           "author": [
                  {
                   "authorId": [{
                            "id": "0000-0002-5728-0264",
                            "provider": "orcid"
                                }],
                   "name": "Ted Tester"
                  }
               ]
         }
```

**Comment by 7048730** [comment]
this currently depends on yaml header of input file

**Comment by 7048730** [comment]
I think, best way to deal with this might be the broker that looks out for yaml header completeness and completes according to the schema. That means the `metadata.o2r` in our db won't be available until the broker has reworked the raw metadata.

**Comment by 7048730** [comment]
changed this in extractor 03861169c72536b0d9fdb4875a099912a6cefba0

raw MD:
```{json}
    "author": [
        {
            "name": "Ted Tester",
            "orcid": null
        }
    ]
```

o2r MD: (requires broker)
```{json}
    "author": [
        {
            "authorId": null,
            "authorName": "Ted Tester"
        }
    ]
```
