### ISSUE TITLE
gdal installation for travis fails

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-meta#20]
installation of the gdal package or some of the dependencies seems to fail lately...
what to do about it?

**Comment by 7048730** [comment]
+ [Travis log](https://travis-ci.org/o2r-project/o2r-meta/jobs/203821012)

**Comment by nuest** [comment]
The reliability problem seems to be in downloading files... nothing we can do about it. Maybe point it out to Travis folks?

**Comment by 7048730** [comment]
what could they do about ubuntu repository availability?

**Comment by 7048730** [comment]
must be these two lines from travis file. if the ppa is unavailable the build fails?
>  - sudo add-apt-repository ppa:ubuntugis/ppa -y
>  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y

**Comment by nuest** [comment]
They cannot do anything about it, but they probably have a local mirror already and it's always good to know about issues users are having.

IMHO if we're not telling Travis then we can close this issue.

**Comment by 7048730** [comment]
Fails since travis update for [Ubuntu Precise 12.04](https://blog.travis-ci.com/2017-05-04-precise-image-updates).

**Comment by 7048730** [comment]
fixed with c7e12cab97febab30a1441b91572fe710416f86e
