### ISSUE TITLE
ORCID 2.0 API support in requirements

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-meta#21]
https://github.com/ORCID/python-orcid/issues/16

**Comment by nuest** [comment]
Do you mean you want to switch using ORCID 2.0 API? Or just update the requirements documentation?

**Comment by 7048730** [comment]
In case they manage to update the python modul in time we can go for simple requirement upgrade. The other option is wrapping the required api parts by ourselves.

**Comment by 7048730** [comment]
removed requirement in 1a2b1a83815514a43805653f7457debd7f02e7ef since we currently use only search calls. might go back to _orcid_ package when we start writing orcid records via API. but that does not seem to be a task for the extractor.
