### ISSUE TITLE
Affiliation and additional tags

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-meta#24]
The matadata object we currently receive from the extractor contains the tags "affiliation" and "affiliation2". I guess this is not wanted. Our state is that there is only one affiliation so also not even an array.
@jansule fyi 

I would like to add two more tags: "researchQuestion" and "hypotheses", both as String arrays.

**Comment by 7048730** [comment]
Okay those are different issues. We had `affiliation2` from example data of jstatsoft, hence it was included. But I can turn it into an array.
I'll also add the other two tags as we discussed a while ago.

**Comment by 7048730** [comment]
@MarkusKonk can we name them `researchQuestions` and `researchHypotheses` and make them both lists (arrays) or do you prefer a string element? it might even be possible to extract both questions and hypotheses when the paper uses a proper ontology for it or by parsing headlines, abstract, etc

**Comment by MarkusKonk** [comment]
research question and hypotheses should be arrays, right. 
Extracting them automatically is a bit tricky I think as it is usually not explicitly stated in the text.

Is it possible that there is more than one affiliation? Otherwise we would not need an array, here.

**Comment by 7048730** [comment]
I think there could be more than one affiliation thought that will not be the common case.
For example, a researcher might be employed at more than one research institution at the same time.
Whether they chose to include this information and how it might be encoded (e.g. `affiliation2`) is not predictable. So we have at least two ways of dealing with this:
1. always only take `affiliation` and ignore the rest
2. make affiliation an array and add all affiliation information we can find

**Comment by MarkusKonk** [comment]
Ok, so let's take an array.
@jansule fyi

**Comment by 7048730** [comment]
included with ec4cae32849bf548dd0a82f9f7f6c1cada91d891

**Comment by jansule** [comment]
In the current version `affiliation` is not an `array` but a `string`.
See here:
```JSON
"author": [
                {
                    "name": "Erik Fraza, James B. Elsner, and Thomas H. Jagger",
                    "affiliation": ""
                }
            ]
```
Rather, it should look like this:
```JSON
"author": [
                {
                    "name": "Erik Fraza, James B. Elsner, and Thomas H. Jagger",
                    "affiliation": [ ]
                }
            ]
```
Please change that to an array, as we agreed upon.

**Comment by 7048730** [comment]
restored with 3f5d7feeda907975586df4adc63cbbe3da34d2d8
