### ISSUE TITLE
[extractor] download and include latest spec

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-meta#25]
Automatically download and  save the latest spec (http://o2r.info/erc-spec/spec/v1) version into ERC during creation in extractor.

cf. https://github.com/o2r-project/erc-spec/issues/9

**Comment by 7048730** [comment]
included with 99a7afe3bd8b8326b8d4a315f76b514b36bfcf5d

**Comment by nuest** [comment]
Would you like to keep this simply as a zip file? I agree putting in a single HTML or PDF might be bikeshedding... but it would be a lot more accessible.

**Comment by 7048730** [comment]
Well that depends on what the purpose of the inclusion of these documents is. I was thinking in terms of digital preservation. The extractor is certainly not generating a pdf file from the markdown of the spec, is it?
I thought of this as "include a reference in case someone wonders what was the specification, ten years later". We should discuss this, when you're back!

**Comment by nuest** [comment]
No, the extractor would not generate the file, see https://github.com/o2r-project/erc-spec/issues/9

Yes, let's decide what we want this for next week.
