### ISSUE TITLE
[extractor] Add identifiers DOI, ...

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-meta#28]
Use case: ERC candidate already has a persistent identifier assigend from former publication.

- [x] extract from Rmd header
- [x] get from http request if title/author is unique

Metadata key:
```json
    "identifier": {
        "doi": "10.9999/test",
        "doiurl": "https://doi.org/10.9999/test",
        "reserveddoi": null
    },
```

**Comment by 7048730** [comment]
included with 35da33e80fcab45b75ada4d7ebdd84fb21d61694
cc @nuest @LukasLohoff

**Comment by 7048730** [comment]
sources for doi retrieval from title + author via http:

- crossref: has no exact matching for any md field, yields too many hits
- datacite: only for data
- orcid: requires orcid
- ...

**Comment by 7048730** [comment]
included with c91b1c12e1f1ee6c04964f10959989e1ef191a35

**Comment by nuest** [comment]
@7048730 Do you have a couple of example compendia? Maybe one with an embedded doi and one where a doi can be found via search?

**Comment by 7048730** [comment]
I fear none of the papers in our current corpus has a doi embedded in the rmarkdown header (which is expected due to publication workflow). So many of them can be found via search, e. g. _TemperatureAndMoistureEffects_.

I will include a doi field in the _metatainer2_. Until then, it is already available in the [o2rmeta extractor testfile](https://github.com/o2r-project/o2r-meta/blame/master/extract/tests/test2.Rmd#L17).
