### ISSUE TITLE
No viewfile attribute in o2r.metadata

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-meta#30]
After pulling the muncher today, the newly added attribute `viewfile` does not exist in o2r.metadata.

**Comment by 7048730** [comment]
Cannot reproduce your error. what's your testset?

**Comment by 7048730** [comment]
viewfile can be `null`, if no main file could be identified automatically. platform should check and except that. the user need to tell in that case

**Comment by 7048730** [comment]
added viewfile array for html files with ce838d7ebc9e6732421dbef1b7d2b690240e7fff
