### ISSUE TITLE
Metadata for Code and Data files

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-meta#33]
So far, `inputfiles` contains information about used files. If I understand it right, this attribute only contains Data and not Script files. Is that right?
On the platform I need information about Code/Script and Data files. Furthermore, they will be handled differently and thus need a clear distinction in the metadata.

I would suggest to only store Data files in `inputfiles` and create an additional attribute `codefiles` or `scriptfiles` that contains Codes/Scripts.

**Comment by 7048730** [comment]
added with 3f5d7feeda907975586df4adc63cbbe3da34d2d8 as `codefiles`
