### ISSUE TITLE
redesign mainfile & viewfiles extraction

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-meta#45]
- R + RMD
- img, html

- `mainfile` <-- best candidate
- `mainfiles` []
- `viewfile` <-- best candidate
- `viewfiles` []

_edit: outdated, see below_

**Comment by nuest** [comment]
Current examples for minimal with .R script and minimal with .Rmd:

- https://github.com/nuest/o2r-loader/tree/accept-workspaces/test/workspace/minimal-script
- https://github.com/nuest/o2r-loader/tree/accept-workspaces/test/workspace/minimal-rmd

**Comment by 7048730** [comment]
concerning the labels, see https://github.com/o2r-project/o2r-meta/issues/49

**Comment by 7048730** [comment]
the links are dead, see https://github.com/o2r-project/o2r-loader/tree/master/test/workspace for reference

**Comment by 7048730** [comment]
included with 88aa6736ef3d2a4e5099c37f62a7fd4bd634d6b7
