### ISSUE TITLE
Remake o2r schema

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-meta#46]
remake schema file according to current platform MD interface

https://github.com/o2r-project/o2r-meta/blob/dev/schema/json/o2r-meta-schema.json

**Comment by 7048730** [comment]
major update done in 0057e284e30b725b0b17059c048f5ab328ca2583
Needs to be finalised (final set of identifiers, interaction, spatial, license many vs. x).

To do:

- [ ] o2r element list for developers, similar to raw MD elements https://github.com/o2r-project/o2r-meta/blob/dev/schema/docs/elements.md
- [ ] upd spec about current mds
- [ ] implement call validator and validate o2r md against o2r schema before setting candidate to false
- [ ] finalise o2r schema

**Comment by nuest** [comment]
Agreed!

**Comment by 7048730** [comment]
@nuest I think, I'm done here from the perspective of o2r meta. Just let me know when you add the validator call, so we can close this issue.

**Comment by nuest** [comment]
is included in https://github.com/o2r-project/o2r-muncher/pull/96
