### ISSUE TITLE
Add parameter to show supported files for extraction

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#51]
For users of `extract` tool, it would be nice to learn about the supported formats without going to the [online documentation](https://github.com/o2r-project/o2r-meta#supported-files-and-formats-for-the-metadata-extraction-process).

For software embedding the `extract` tool, it would be useful if this list comes in a parseable format, e.g. "new line delimited", so that it may be used in their own workflow.

The list could be file formats and file names, like this:

```bash
$ python o2rmeta.py extract -formats

*.r
*.rmd
*.shp
bagit.txt
```

I am unsure about the placeholders/regexes here, because within `extract` [just the file extension is checked](https://github.com/o2r-project/o2r-meta/blob/0d045f30884b4ab7f86fbfae27993fcf6fa0f1be/extract/metaextract.py#L829). The output could also be something like

```
    extensions: .r .rmd .shp
    files: bagit.txt
```

**Comment by 7048730** [comment]
included with 1f627ae894602218c99a2ec8859c5d0430e17b98
