### ISSUE TITLE
Installation problems with "dev" branch on Ubuntu

### ISSUE THREAD

**Issue by LukasLohoff** [o2r-project/o2r-meta#55]
The dev branch requires Pyhton 3.6, which is not officially supported for Ubuntu 16.04 or 16.10. I tired the PPA repository `ppa:jonathonf/python-3.6` (with these instructions http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/). Installation completes, but when running the meta tool through the o2r-loader I now get the error

`ModuleNotFoundError: No module named 'apt_pkg'`

That module isn't available for python3.6, at least with the repository I used. See https://stackoverflow.com/a/41722610

Additional issue: The command `pip install -r requirements.txt` doesn't work for pyhton 3.5/3.6, it installed the modules for python 2.7 only. I had to run `pip3 install --user -r requirements.txt` for python 3.5 and `python3.6 -m pip install --user -r requirements.txt` for python 3.6

To then get the loader to actually use python3.6 I had to set the environment variable `LOADER_META_TOOL_EXE='python3.6 ../o2r-meta/o2rmeta.py'`

**Comment by 7048730** [comment]
have a look at my travis setup in dev branch, where everything works fine (also ubuntu). perhaps you can use that if you need to try the dev branch. the alternative is to waiting until I finished the next master merge

**Comment by 7048730** [comment]
@LukasLohoff did you get the muncher to run? there were a lot of changes to both the muncher and the meta. Maybe it is worth trying to launch this again. Otherwise if you have nothing to add, I would like to close this issue.

**Comment by nuest** [comment]
+1 for closing, as the loader will soon only be used from within a container, then this issue is gone: 

- https://github.com/o2r-project/o2r-loader/pull/36
- https://github.com/o2r-project/o2r-muncher/pull/73
