### ISSUE TITLE
Inconsistency in o2r-meta-schema.json

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-meta#6]
Throughout the json there is an attribute called `depends` which is called `dependency` in the `required`-attribute. See here https://github.com/o2r-project/o2r-meta/blob/d708922e354d5e8c13292c3a69e19035eeffd585/schema/json/o2r-meta-schema.json#L92

**Comment by 7048730** [comment]
fixed in d5079a7153b67b2368d96a54e7cd8775c58ea12a
