### ISSUE TITLE
Provenance property not supported by MongoDB

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#60]
The provenance object contains keys [not supported by MongoDB](https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names) (for security reasons, as `.` is used to navigate through documents), namely `.`:

```json
{
"provenance": {
        "/tmp/o2r/compendium/bsWlK/data/document.Rmd": "parsers.parse_rmd parse"
    }
}
```

This is valid JSON, of course.

Still, would you be fine with a different layout of the provenance? Such as

```json
{
"provenance": {
        "command": "parsers.parse_rmd parse",
        "file": "/tmp/o2r/compendium/zzVrh/data/document.Rmd"
    }
}
```

Happy to provide the PR as I have changed this locally already.

**Comment by 7048730** [comment]
So I cant use any _filename.extension_ because there is a dot in it? man, there is growing an opinion about mongo :)

**Comment by 7048730** [comment]
Ok, I looked it up and I really must say this seemed to me like the most stupid restriction with dbs I have encountered so far, but it was even excelled by their official proposed solution:

> Replace control chars with their unicode equivalents U+FF04 (i.e. “＄”) and U+FF0E (i.e. “．”).

**Comment by nuest** [comment]
I agree with your sentiment on the proposed solution... but because I do not have a clear understanding on what the `provenance` element will eventually look like (or is this all that you plan?), I hoped this would be a small change and actually work well with additional provenance information in the future.

**Comment by 7048730** [comment]
it's not about provencance, I could drop that easily. no, the dot appears in a lot of other elements like all filelists, spatial, ... it is an easy fix to have them escaped but that makes terrible metadata, so they must be unescaped everytime which is prone to errors in this chain bson, json, (xml). totally necessary and yet no way around which bothers me a lot

**Comment by nuest** [comment]
There is no issue for the extractor, so we could also leave it as it is and move the handling of this problem to the microservice.

**Comment by 7048730** [comment]
since the microservice communicates with the mongo db instance that might be a clean way. alternatively I could make option to have the extractor output mongo bson just like the -xml flag

**Comment by nuest** [comment]
There is no issue for the extractor, so we could also leave it as it is and move the handling of this problem to the microservice.
