### ISSUE TITLE
Use only relative paths in metadata after extraction

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#61]
The extracted metadata, see excerpt from `metadata_raw.json` below, should _not_ use full paths, but relative paths. The path below (a) exposes server-side configuration, and (b) becomes meaningless when the compendium is moved. For example

```json
"mainfile": "/tmp/o2r/compendium/wyRRV/data/document.Rmd",
    "mainfile_candidates": [
        "/tmp/o2r/compendium/wyRRV/data/document.Rmd"
    ]
```

should be

```json
"mainfile": "data/document.Rmd",
    "mainfile_candidates": [
        "data/document.Rmd"
    ]
```

I guess you could also remove `paperSource` now?

**Comment by 7048730** [comment]
when switching to modular parses I removed the function for relative paths because I thought it was useless, that's why its gone. I can fix that.

**Comment by 7048730** [comment]
todo fix mainfile relative path sperately or pipe mainfile element through displayfile parser
