### ISSUE TITLE
Inconsistency between o2r-schema.md and o2r-meta-schema.json

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-meta#8]
In [o2r-schema.md, section 2, main schema](https://github.com/o2r-project/o2r-meta/blob/d708922e354d5e8c13292c3a69e19035eeffd585/schema/docs/o2r-schema.md) the attributes `dateCreated`, `paperLanguage`, `recordDateCreated` and `softwarePaperCitation` are marked as **optional**, whereas in [o2r-meta-schema.json](https://github.com/o2r-project/o2r-meta/blob/d708922e354d5e8c13292c3a69e19035eeffd585/schema/json/o2r-meta-schema.json#L89-L101) they are marked as **required**.

**Comment by 7048730** [comment]
this is due to emancipation efforts from codemeta, where one of the documents represents an older stage. I will update the docs soon.

**Comment by 7048730** [comment]
fixed in d5079a7153b67b2368d96a54e7cd8775c58ea12a
