### ISSUE TITLE
add version tag to filename for md files generated

### ISSUE THREAD

**Issue by 7048730** [o2r-project/o2r-meta#80]
according to Spec seg. "Secondary metadata files":

>Metadata documents SHOULD be named according to the used standard/model, format/encoding, and 
 version, e.g. datacite40.xml or zenodo_sandbox10.json, and SHOULD use a suitable mime type.

will be updated in spec to reflect version tag contribution added at brokering

**Comment by 7048730** [comment]
use `Settings.outputfile` per mapping to handle this, i.e. keep maps up to date

**Comment by 7048730** [comment]
@nuest I would like to add this now. can you tools cope with filesnames like `zenodo14.json` when reading the metadata? Because the version number might produce constantly changing filenames.

**Comment by nuest** [comment]
Yes, no problem on my end.

Just let me know if I can trust the alphabetical ordering, or if I should parse the file name and use [semantic versioning sort](https://www.npmjs.com/package/semver-sort) or similar. And if there is any seperator like `_v`.
