### ISSUE TITLE
Support arbitrary projections for spatial metadata extraction

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#9]
Support any well-defined projections, which are transformed to WGS84, for spatial metadata.

Probably need to use [proj4](http://proj4.org/projections/index.html) for this:

- https://gis.stackexchange.com/questions/78838/how-to-convert-projected-coordinates-to-lat-lon-using-python

**Comment by 7048730** [comment]
Good addition. I'll take a look into this soon.

**Comment by 7048730** [comment]
proj4 is a handy tool most suitable for this task.

```python
from pyproj import Proj, transform

inProj = Proj(init='epsg:3857')
outProj = Proj(init='epsg:4326')
x1,y1 = -11705274.6374,4826473.6922
x2,y2 = transform(inProj,outProj,x1,y1)
print(x2,y2)
```

to include this, the extractor would need to detect the projection, which might be impossible
