### ISSUE TITLE
Extract licenses from erc.yml

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-meta#90]
When loading a complete ERC in the reproducibility service, the licenses (our own structure, see [ERC spec](http://o2r.info/erc-spec/spec/#license-metadata)) must be extracted from `erc.yml`.

See also https://github.com/o2r-project/o2r-muncher/issues/91

@7048730 I'd be grateful if you could outline the steps to add another parser in the README, I'd be happy to give it a go to implement it.

**Comment by 7048730** [comment]
@nuest good idea, I will describe how to do it soon
